[package]
name = "image_converter"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
webp = "0.1.3"
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
